// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADKibYNaiHdKnfWzF5QgqiZhvCnyPpvTg',
    appId: '1:1037811745197:web:717ddcd5aae76b2536e124',
    messagingSenderId: '1037811745197',
    projectId: 'appsekd',
    authDomain: 'appsekd.firebaseapp.com',
    storageBucket: 'appsekd.firebasestorage.app',
    measurementId: 'G-6TF4Y7YQ56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2BbwIB-cDcls3QqR2b-PGrmMcxF6g6Ug',
    appId: '1:1037811745197:android:f8a1e6c1431907f036e124',
    messagingSenderId: '1037811745197',
    projectId: 'appsekd',
    storageBucket: 'appsekd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADKibYNaiHdKnfWzF5QgqiZhvCnyPpvTg',
    appId: '1:1037811745197:web:d6e2f86561e5944436e124',
    messagingSenderId: '1037811745197',
    projectId: 'appsekd',
    authDomain: 'appsekd.firebaseapp.com',
    storageBucket: 'appsekd.firebasestorage.app',
    measurementId: 'G-9BHG4WMF1R',
  );
}
